/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package DGDecryptor;

import java.io.BufferedReader;
import java.io.InputStreamReader;

public class App {

    public static String getGreeting() {
        return "Hello World!";
    }

    public class DescifradoSanJuan {
    }

        public static void main(String[] args) throws Exception{
            BufferedReader reader = new BufferedReader(
                    new InputStreamReader(System.in)
            );
            String linea = reader.readLine();
            System.out.println(CryptorSJ.descifradoSanJuan(linea));
        }
    
}
